# Observations
TROPOMIvXX: # version is specified for each instrument
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'centers'
  PARSER: 'read_TROPOMIvXX'
  DATA_FIELDS: 
    N_OBS: 'nobs'
    N_EDGES: 'nlevels'
    N_CENTERS: 'nlayers'
    SURFACE_PRESSURE: 'surface_pressure'
    DELTA_PRESSURE: 'dp' 
    PRESSURE_WEIGHT: 'dry_air_subcolumns'
    LATITUDE: 'latitude_center'
    LONGITUDE: 'longitude_center'
    TIME: 'time'
    AVERAGING_KERNEL: 'xch4_column_averaging_kernel'
    PRIOR_PROFILE: 'ch4_profile_apriori'
    SATELLITE_COLUMN: 'xch4'
    QUALITY_FLAG: 'none'

GOSATv9_0: 
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'edges'
  PARSER: 'read_GOSATv9_0'
  DATA_FIELDS:
    N_OBS: 'n'
    N_EDGES: 'm'
    PRESSURE_EDGES: 'pressure_levels'
    PRESSURE_WEIGHT: 'pressure_weight'
    LATITUDE: 'latitude'
    LONGITUDE: 'longitude'
    TIME: 'time'
    AVERAGING_KERNEL: 'xch4_averaging_kernel'
    PRIOR_PROFILE: 'ch4_profile_apriori'
    SATELLITE_COLUMN: 'xch4'
    QUALITY_FLAG: 'xch4_quality_flag'

OCO2_v11.1:
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'edges'
  PARSER: 'read_satellite_file.py'
  DATA_FIELDS:
    N_OBS: 'sounding_id'
    N_EDGES: 'levels'
    PRESSURE_EDGES: 'pressure_levels'
    PRESSURE_WEIGHT: 'pressure_weight'
    LATITUDE: 'latitude'
    LONGITUDE: 'longitude'
    TIME: 'time'
    AVERAGING_KERNEL: 'xco2_averaging_kernel'
    PRIOR_PROFILE: 'co2_profile_apriori'
    SATELLITE_COLUMN: 'xco2'
    QUALITY_FLAG: 'none'

# Model
MODEL: 
  LEVEL_EDGE_FILE_FORMAT: 'GEOSChem.LevelEdgeDiags.*_0000z.nc4' # 20150301
  CONCENTRATION_FILE_FORMAT: 'GEOSChem.SpeciesConc.*_0000z.nc4' #20150301
  PRESSURE_EDGES: 'Met_PEDGE'
  CONCENTRATION_AT_PRESSURE_CENTERS: 'SpeciesConc_CH4'
  LATITUDE: 'lat'
  LONGITUDE: 'lon'
  TIME: 'time'