# Observations
TROPOMIvXX: # version is specified for each instrument
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'centers'
  PRESSURE_EDGES: '' 
  PRESSURE_WEIGHTING: ''
  LATITUDE: ''
  LONGITUDE: ''
  SATELLITE_COLUMN: ''
  PARSER: 'read_TROPOMIvXX'

GOSATvXX: 
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'edges'
  PRESSURE_EDGES: ''
  PRESSURE_WEIGHTING: ''
  LATITUDE: ''
  LONGITUDE: ''
  SATELLITE_COLUMN: ''
  PARSER: 'read_GOSATvXX'

AIRSvXX:
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'edges'
  PRESSURE_EDGES: ''
  PRESSURE_WEIGHTING: ''
  LATITUDE: ''
  LONGITUDE: ''
  SATELLITE_COLUMN: ''
  PARSER: 'read_GOSATvXX'

# Model
MODEL: 
  PRESSURE_EDGES: ''
  LATITUDE: ''
  LONGITUDE: ''
  DRY_AIR: ''