# Change these before your run the script.
LOCAL_SETTINGS:
  REPROCESS: 'True'
  SAVE_SATELLITE_DATA: 'True'
  PARSER: 'OCO2_v11.1_preprocessed'
  OBS_DIR: '/Users/Elise/Downloads/OCO-2'
  OBS_FILE_FORMAT: 'oco2_20141*.nc'
  MODEL_DIR: '/Users/Elise/Downloads/GEOSChem_201410'
  LEVEL_EDGE_FILE_FORMAT: 'GEOSChem.LevelEdgeDiags.*.nc4' 
  CONCENTRATION_FILE_FORMAT: 'GEOSChem.SpeciesConc.*.nc4' 
  SAVE_DIR: '/Users/Elise/Downloads/outdir'
  FILE_LENGTH_THRESHOLD: 1.0e+6

# Observations
OCO2_v11.1_preprocessed:
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'edges'
  PARSER: 'read_OCO2_v11_1_preprocessed'
  DATA_FIELDS:
    N_OBS: 'sounding_id'
    N_EDGES: 'levels'
    PRESSURE_EDGES: 'pressure_levels'
    PRESSURE_WEIGHT: 'pressure_weight'
    LATITUDE: 'latitude'
    LONGITUDE: 'longitude'
    TIME: 'time'
    AVERAGING_KERNEL: 'xco2_averaging_kernel'
    PRIOR_PROFILE: 'co2_profile_apriori'
    SATELLITE_COLUMN: 'xco2'
    QUALITY_FLAG: 'none'

TROPOMIvXX: # version is specified for each instrument
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'centers'
  PARSER: 'read_TROPOMIvXX'
  DATA_FIELDS: 
    N_OBS: 'nobs'
    N_EDGES: 'nlevels'
    PRESSURE_EDGES: 'pressure_edges' # This variable does not
    # exist in the TROPOMI files and needs to be created in the
    # parser.
    # N_CENTERS: 'nlayers'
    # SURFACE_PRESSURE: 'surface_pressure'
    # DELTA_PRESSURE: 'dp' 
    PRESSURE_WEIGHT: 'dry_air_subcolumns'
    LATITUDE: 'latitude_center'
    LONGITUDE: 'longitude_center'
    TIME: 'time'
    AVERAGING_KERNEL: 'xch4_column_averaging_kernel'
    PRIOR_PROFILE: 'ch4_profile_apriori'
    SATELLITE_COLUMN: 'xch4'
    QUALITY_FLAG: 'none'

GOSATv9_0:
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'edges'
  PARSER: 'read_GOSATv9_0'
  DATA_FIELDS:
    N_OBS: 'n'
    N_EDGES: 'm'
    PRESSURE_EDGES: 'pressure_levels'
    PRESSURE_WEIGHT: 'pressure_weight'
    LATITUDE: 'latitude'
    LONGITUDE: 'longitude'
    TIME: 'time'
    AVERAGING_KERNEL: 'xch4_averaging_kernel'
    PRIOR_PROFILE: 'ch4_profile_apriori'
    SATELLITE_COLUMN: 'xch4'
    QUALITY_FLAG: 'xch4_quality_flag'

# Model
MODEL:
  DATA_FIELDS:
    PRESSURE_EDGES: 'Met_PEDGE' # Not PEDGEDRY?
    CONC_AT_PRESSURE_CENTERS: 'SpeciesConcVV_CO2' # todo: CO2 vs CH4. 
    LATITUDE: 'lat'
    LONGITUDE: 'lon'
    TIME: 'time'
    LEV: 'lev'
    ILEV: 'ilev'