# Generic config format for a satellite that specifies the 
# vertical grid using pressure edges.
SATELLITE_USING_PRESSURE_EDGES: 
  AVERAGING_KERNEL_USES_CENTERS_OR_EDGES: 'centers' or 'edges'
  OBS_DIR: 'location_of_data'
  FILE_NAME_FORMAT: 'file_name_format*.nc'
  PARSER: 'parser_name_in_parsers.py'
  DATA_FIELDS:
    N_OBS: 'observation_name'
    N_EDGES: 'vertical_level_edges'  # What is the difference between
    PRESSURE_EDGES: 'dimension_name' # these two fields?
    PRESSURE_WEIGHT: 'dimension_name'
    LATITUDE: 'dimension_name'
    LONGITUDE: 'dimension_name'
    TIME: 'dimension_name'
    AVERAGING_KERNEL: 'dimension_name'
    PRIOR_PROFILE: 'dimension_name'
    SATELLITE_COLUMN: 'dimension_name'
    QUALITY_FLAG: 'optional_dimension_name_or_none'